import type { Metadata } from "next";
import Link from "next/link";

import DataSourcesList from "@/components/DataSourcesList";
import { SECURITY_POLICY_URL } from "@/lib/links";

export const metadata: Metadata = {
  title: "How this works — Sunshine Ledger",
  description:
    "Where Sunshine Ledger's bill data comes from, how the plain-language summaries are produced, and what this site does not claim.",
};

/** Public methodology page.
 *
 *  A site that publishes AI-written summaries of legislation owes readers an
 *  account of how they were produced. This deliberately includes the limits
 *  and the things that have gone wrong, not just the happy path — a
 *  methodology page that only lists strengths isn't a methodology page.
 */
export default function MethodologyPage() {
  return (
    <article className="prose-sm max-w-none">
      <h1 className="text-2xl font-bold text-ledger-900">How this works</h1>
      <p className="mt-1 text-sm text-slate-500">
        Where the data comes from, how the summaries are written, and what this site does not claim.
      </p>

      <section className="mt-6">
        <h2 className="text-base font-semibold text-ledger-900">Where bills come from</h2>
        <ul className="mt-2 space-y-1.5 text-sm text-slate-700">
          <li>
            <span className="font-medium">Florida state bills</span> — LegiScan, which republishes
            the Legislature&apos;s own records.
          </li>
          <li>
            <span className="font-medium">Jacksonville</span> — the city&apos;s Legistar system, the
            same records the City Council uses.
          </li>
          <li>
            <span className="font-medium">Miami</span> — the city&apos;s Granicus iQM2 system.
          </li>
        </ul>
        <p className="mt-2 text-sm text-slate-700">
          Every claim on this site stores the source it came from, along with when that source was
          retrieved. Those links are shown on each bill. Where a summary and the source disagree,
          the source is correct.
        </p>
      </section>

      <section className="mt-6">
        <h2 className="text-base font-semibold text-ledger-900">How summaries are written</h2>
        <p className="mt-2 text-sm text-slate-700">
          Summaries are generated by an AI language model running on private hardware — no bill text
          is sent to a third-party AI service. Each bill gets two: what it does, and who it affects.
        </p>
        <p className="mt-2 text-sm text-slate-700">
          The model is given the filed bill text where available, rather than the short official
          blurb. That change measurably improved accuracy: on one public-records bill, the blurb
          produced &ldquo;the available text does not specify a particular affected group&rdquo;,
          while the full text correctly identified social workers and the commission overseeing
          their licensure.
        </p>
        <p className="mt-2 text-sm text-slate-700">
          The prompts instruct the model to use only what the text supports, to avoid speculating
          about intent or effects, and to avoid words implying a value judgement. Each stored
          summary records which model wrote it.
        </p>
      </section>

      <section className="mt-6">
        <h2 className="text-base font-semibold text-ledger-900">Bill Says, Interpretation, Expected Effect, Who it affects</h2>
        <p className="mt-2 text-sm text-slate-700">
          Bill pages separate three kinds of statement so you always know which one you are reading.
        </p>
        <ul className="mt-2 space-y-1.5 text-sm text-slate-700">
          <li>
            <span className="font-medium">Bill Says</span> — quotes from the bill itself. An AI model picks the
            provisions, but every quote is checked word for word against the bill text, and any quote that doesn&apos;t
            match is thrown out.
          </li>
          <li>
            <span className="font-medium">Interpretation</span> — what the change means. Where Florida legislative
            staff have published an analysis, their reading is shown first, condensed by AI and labeled with the
            committee and date. Sunshine Ledger&apos;s own AI interpretation of the bill text is shown separately and
            labeled as such, with the assumptions it depends on.
          </li>
          <li>
            <span className="font-medium">Expected Effect</span> — what may happen. These are forecasts, not facts,
            and not legal or financial advice. Staff fiscal findings are restated as staff wrote them, including
            &ldquo;none&rdquo; or &ldquo;indeterminate&rdquo;. Sunshine Ledger only describes effects that a
            specific section of the bill creates; each must cite that section and use words like &ldquo;may&rdquo;
            or &ldquo;could&rdquo;, or it is not published.
          </li>
          <li>
            <span className="font-medium">Who it affects</span> — who the bill directly applies to, one group at a
            time: what changes for them (an obligation, eligibility, protection, cost, service, or prohibition), the
            sentence of the bill that makes the change, and any conditions or exceptions the bill states. Each of those
            sentences is checked word for word against the bill text; an exception the bill doesn&apos;t state is never
            listed, and a missing one isn&apos;t filled in because it seems likely. Possible knock-on effects, like
            prices, belong under Expected Effect instead. The wording follows the bill&apos;s status and its own
            effective date: &ldquo;would apply&rdquo; while it is pending, &ldquo;will apply beginning&rdquo; once
            enacted but not yet in effect, &ldquo;applies&rdquo; once in effect, and &ldquo;would have
            applied&rdquo; if it failed. Belonging to a group doesn&apos;t mean every condition applies to you.
          </li>
        </ul>
        <p className="mt-2 text-sm text-slate-700">
          Every AI-written block says whether it has been reviewed by a person. A new version starts unreviewed,
          even if the one it replaced was reviewed. Earlier versions stay visible on the page rather than being
          silently rewritten.
        </p>
        <p className="mt-2 text-sm text-slate-700">
          <span className="font-medium">Not yet evaluated</span> means we haven&apos;t analyzed that part yet — not
          that there is nothing to find. <span className="font-medium">Insufficient evidence</span> means we looked,
          within the scope stated, and couldn&apos;t support a statement.
        </p>
      </section>

      <section className="mt-6">
        <h2 className="text-base font-semibold text-ledger-900">Limits worth knowing</h2>
        <ul className="mt-2 space-y-1.5 text-sm text-slate-700">
          <li>
            <span className="font-medium">Summaries are not individually reviewed by a person.</span>{" "}
            Quality was checked against samples before switching the pipeline on, but no human reads
            every summary before it appears here.
          </li>
          <li>
            <span className="font-medium">AI models get things wrong.</span> They can omit
            conditions, blur distinctions, or state something with more confidence than the text
            supports. Read the linked source for anything that matters to you.
          </li>
          <li>
            <span className="font-medium">Very long bills are truncated</span> before summarizing,
            so a summary may not reflect later sections of a lengthy bill.
          </li>
          <li>
            <span className="font-medium">Coverage is partial.</span> Florida state bills plus two
            cities. A bill not appearing here does not mean it does not exist.
          </li>
          <li>
            <span className="font-medium">Maps are approximate.</span> Shading is at county or
            legislative-district level using U.S. Census boundaries — never per-address.
          </li>
        </ul>
      </section>

      <section id="data-sources" className="mt-6 scroll-mt-4">
        <h2 className="text-base font-semibold text-ledger-900">Data sources and freshness</h2>
        <p className="mt-1 text-sm text-slate-700">
          When each source was last checked, what it covers, and what it doesn&apos;t. A check that found
          nothing new still counts as a check.
        </p>
        <DataSourcesList />
      </section>

      <section className="mt-6">
        <h2 className="text-base font-semibold text-ledger-900">What this site does not do</h2>
        <ul className="mt-2 space-y-1.5 text-sm text-slate-700">
          <li>It does not score, rate, or rank legislators.</li>
          <li>
            It does not connect bills to candidates, parties, or races. The election calendar is
            shown as civic context only.
          </li>
          <li>
            It does not assign sentiment or stance. News headlines are matched by keyword and shown
            unscored; their presence is not a claim about a bill.
          </li>
          <li>It does not accept open or crowdsourced edits.</li>
        </ul>
      </section>

      <section id="corrections" className="mt-6 scroll-mt-4">
        <h2 className="text-base font-semibold text-ledger-900">Found something wrong?</h2>
        <p className="mt-2 text-sm text-slate-700">
          Every bill page has &ldquo;Report a problem with this bill&rdquo;, and every analysis block has &ldquo;Flag
          this block&rdquo;. Say what&apos;s wrong and, if you can, add a link or a quote that shows it; evidence helps
          but isn&apos;t required. A report goes to a person for review. It never changes the site by itself, and many
          reports about the same statement count as one case, not as proof.
        </p>
        <h3 className="mt-3 text-sm font-semibold text-ledger-900">What you may see on a page</h3>
        <ul className="mt-1 space-y-1.5 text-sm text-slate-700">
          <li>
            <span className="font-medium">Disputed — under review:</span> a reviewer found a credible challenge to a
            material or critical statement. The statement stays up with this label until a decision is published.
            Sunshine Ledger doesn&apos;t hide statements while they&apos;re reviewed, so filing a complaint can&apos;t
            make something disappear.
          </li>
          <li>
            <span className="font-medium">Corrected, Updated, Clarified, Retracted [date]:</span> what changed and when.
            A correction means Sunshine Ledger got it wrong; an update means new information arrived; a clarification
            fixes wording that could mislead; a retraction means the statement is no longer supported. Material and
            critical changes also say what the earlier version said and why it changed.
          </li>
          <li>
            <span className="font-medium">Source corrected:</span> the source changed its own record, for example a
            new version of a staff analysis. That isn&apos;t a Sunshine Ledger error and isn&apos;t described as one.
          </li>
          <li>
            <span className="font-medium">Response from [name]:</span> a reply from a person or organization named on
            the page, shown as they wrote it, with how their identity was checked (through contact details on their
            official filings). A response isn&apos;t evidence by itself and doesn&apos;t change a finding.
          </li>
        </ul>
        <h3 className="mt-3 text-sm font-semibold text-ledger-900">How reviews are handled</h3>
        <ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-slate-700">
          <li>Possible harm comes first, not the number of reports.</li>
          <li>
            Targets, not guarantees: critical issues (wrong identity, false attribution, an unsupported accusation)
            are triaged within 2 days and decided within 7; material issues within 7 and 30 days; minor fixes as time
            allows. Sunshine Ledger is run by one person. Each case records its dates, so missed targets are counted, not hidden.
          </li>
          <li>
            Every reviewed report gets a recorded decision and reason, including &ldquo;no change&rdquo;. A case
            reopens if material new evidence arrives, and the earlier decision is kept.
          </li>
          <li>
            Corrections to AI-generated analysis count as Sunshine Ledger corrections and are listed like any other.
            Regenerating analysis after a method change isn&apos;t a correction; it&apos;s logged as a methodology
            change.
          </li>
          <li>
            Nothing is corrected quietly. The earlier version, the corrected version and the evidence stay reachable
            from the page.
          </li>
        </ul>
        <p className="mt-2 text-sm text-slate-700">
          Material and critical changes across the site are listed on the{" "}
          <Link href="/corrections" className="text-sunshine-700 underline">corrections log</Link>.
        </p>
      </section>

      <p className="mt-8 text-xs text-slate-500">
        See also the{" "}
        <Link href="/privacy" className="underline hover:text-slate-600">
          privacy and terms
        </Link>{" "}
        page and the{" "}
        <a href={SECURITY_POLICY_URL} className="underline hover:text-slate-600">
          security policy
        </a>
        .
      </p>
    </article>
  );
}
