"""add flags table

Revision ID: 3d8dca167085
Revises: 57aceafc5f99
Create Date: 2026-07-25 03:29:01.342368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3d8dca167085'
down_revision: Union[str, None] = '57aceafc5f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags',
    sa.Column('bill_entity_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('reporter_email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_bill_entity_id'), 'flags', ['bill_entity_id'], unique=False)
    op.create_index(op.f('ix_flags_status'), 'flags', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flags_status'), table_name='flags')
    op.drop_index(op.f('ix_flags_bill_entity_id'), table_name='flags')
    op.drop_table('flags')
    # ### end Alembic commands ###
