"""add bill description column

Revision ID: 73c38cab2d74
Revises: 3d8dca167085
Create Date: 2026-07-25 04:33:43.100029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '73c38cab2d74'
down_revision: Union[str, None] = '3d8dca167085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'description')
    # ### end Alembic commands ###
